resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/bilalally808/concourse1
    branch: master

- name: base
  type: docker-image
  source:
    repository: busybox
    tag: latest


jobs:
- name: hello-world-job
  public: true
  plan:
      - get: my-git-repo
      - get: base
      - task: print-hello
        image: base
        config:
          inputs:
          - name: my-git-repo
          platform: linux
          run:
            path: my-git-repo/test.sh
