resources:
- name: my-git-repo
  type: git
  source:
    uri: https://github.com/bilalally808/concourse1
    branch: master

jobs:
- name: hello-world-job
  public: true
  plan:
  - get: my-git-repo
  - task: task_print-hello-world
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      run:
        path: ./my-git-repo/test.sh
